# Use official Node.js image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json first for caching
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install antd dayjs xlsx file-saver


# Copy the rest of the application
COPY . .

# Expose port (match your app port)
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
